from task2_functions import *

''' 
#==============================================================================#
#  *DO NOT EDIT THIS FILE!*  ALL YOUR CODE GOES IN task2_functions.py          #
#   Use this file to interactively test your code                              #
#==============================================================================#
'''

menu = "Test which?\n1. Date Functions\n2. Boolean Functions\n3. Exponential\n4. QUIT\nChoice: "
choice = input(menu)
while choice != "4":
    
    if choice == "1":
        #Tests the 2 date functions
        date_choice = input("\n1. day_of_apr_1()\n2. which_term()\nChoice: ")
        
        #sub-menu for the 2 date options
        if date_choice == "1":
            #test day_of_apr_1()
            year = int(input("Enter a year (e.g., 1984): "))
            weekday = day_of_apr_1(year)
            print(f"April 1st in {year} is a {weekday}")

        elif date_choice == "2":
            #test which_term()
            month_num = int(input("Enter the month number (e.g., January is month 1): "))
            day_num = int(input("Enter the day of the month: "))
            school_term = which_term(month_num, day_num)
            
            print(f"Day {day_num} in month #{month_num} is in {school_term}")

        else:
            print("Invalid menu selection")
    
    
    elif choice == "2":
        #Tests the 2 boolean functions
        bool_choice = input("\n1. is_factorable()\n2. dicey_rolls()\nChoice: ")
        
        #sub-menu for the 2 date options
        if bool_choice == "1":
            #test is_factorable()
            print(f"Enter the values of a, b, and c in ax{chr(178)} + bx + c")
            a_value = int(input("a: "))
            b_value = int(input("b: "))
            c_value = int(input("c: "))
            if is_factorable(a_value, b_value, c_value):
                print(f"{a_value}x{chr(178)} + {b_value}x + {c_value} CAN be factored")
            else:
                print(f"{a_value}x{chr(178)} + {b_value}x + {c_value} CANNOT be factored")
                

        elif bool_choice == "2":
            #test dicey_rolls()
            num_sides = int(input("How many sides are on the dice (must be at least 4)?: "))
            
            if dicey_rolls(num_sides):
                print("You win!")
            else:
                print("You lose!")

        else:
            print("Invalid menu selection")
            
            
    elif choice == "3":
        #Tests exponential_function()
        print(f"Enter the values of a, b, and c in f(x) = a(b){chr(739)} + c")
        a_value = float(input("a: "))
        b_value = float(input("b: "))
        c_value = float(input("c: "))
        
        results = exponential_function(a_value, b_value, c_value)
        print(results)

    choice = input("\n" + menu)